# Header
#导航栏
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open

#社交

#代码高亮主题
highlight_theme: mac

#主页文章节选: 描述信息选用那些,具体参照butterfly官网配置

#相关推荐(文章下的推荐)
related_post:
  enable: true
  limit: 6 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

#阅读模式
readmode: false

#侧边栏设置: 在首页
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手机页面（ 显示宽度 < 768px ）是否显示aside内容
  position: right # left or right
  card_author:
    enable: true
    description: 儿子,丈夫,父亲
    button:
      icon: fab fa-github
      text: GitHub
      link: https://github.com/
  card_announcement: #公告
    enable: true
    content: 一路坎坷走来,势必嫉恶如仇!
  card_recent_post: #最新文章
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories: #分类
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags: #标签
    enable: true
    limit: 40 # if set 0 will show all
    color: true
  card_archives: #归档
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo: #网站资讯
    enable: true
    post_count: true
    last_push_date: true

#访问人数
busuanzi:
  site_uv: false #访客数
  site_pv: false #访问量
  page_pv: false #总访问量

#运行时间
runtimeshow:
  enable: false
  publish_date: 6/7/2018 00:00:00  
  
#文章封面


#顶部图
index_img: https://w.wallhaven.cc/full/g8/wallhaven-g83m3d.jpg #主页的 top_img
archive_img: https://w.wallhaven.cc/full/2e/wallhaven-2eroxm.jpg #归档页面的 top_img
tag_img: https://w.wallhaven.cc/full/x8/wallhaven-x81z9d.jpg #tag 子页面 的 默认 top_img
category_img: https://w.wallhaven.cc/full/m9/wallhaven-m9pzz9.jpg # category 子页面 的 默认 top_img

#头像
avatar:
  img: https://dss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2939425441,2024243876&fm=111&gp=0.jpg
  effect: false # 头像会一直转圈

#页脚
#博客年份设置 和 页脚自定义文本
footer:
  owner:
    enable: true
    since: 2020
  custom_text: 为人类进化而努力!

#字数统计 
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

#页面加载动画preloader(在github上乱码)

#背景特效(静止彩条)
canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false  #设置是否每次点击都更换綵带
  mobile: false # false 手机端不显示 true 手机端显示

#自定义主题颜色
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"


note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: false
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0
  
error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background: 
 
#评论配置 


#网站首页座右铭
subtitle:
  enable: true
  effect: true
  loop: true
  source: 1
  sub:
    - 今日事&#44;今日毕
    - Never put off till tomorrow what you can do today
    
#本地搜索功能
search:
  path: search.xml
  field: post
  content: true
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
# Content
excerpt_link: Read More

#图片大图查看模式
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
